data_crawling:
  exclude_phrase:
    - "제품을 협찬받아 작성되었습니다"
    - "제품을 제공받아 작성하였습니다"
    - "협찬을 받아 작성된 포스팅입니다"
    - "소정의 사례금을 받고 작성되었습니다"
    - "사례금을 받아 작성한 글입니다"
    - "제공한 금전적 보상을 받고 작성되었습니다"
    - "제품을 협찬받고 소정의 사례금을 받아 작성되었습니다"
    - "협찬과 사례금을 받아 작성된 리뷰입니다"
    - "제품 협찬과 함께 작성되었습니다"
    - "제품과 사례금을 제공받아 작성되었습니다"
    - "광고를 포함하고 있습니다"
    - "홍보를 목적으로 작성되었습니다"

  exclude_hashtag:
    - "#광고"
    - "#협찬"
    - "#스폰서"
    - "#지원받음"
    - "#유료광고"
    - "#광고포함"
    - "#제휴"
    - "#파트너십"
    - "#홍보"
    - "#광고제휴"
    - "#광고리뷰"
    - "#프로모션"
    - "#AD"
    - "#Sponsored"
    - "#SponsoredPost"
    - "#PaidPartnership"
    - "#PaidPromotion"
    - "#Promotion"
    - "#PR"
preprocessing:
  filter:
    - lgstanbymeclub
    - imsanbu
    - campingfirst

gptapi:
  parameters:
    model: "gpt-4o"
    temperature: 0.5
    stream: False

  sentiment:
    instructions: |
      넌 글을 요약하는 전문가야. 어떤 제품에 대한 리뷰 원문(raw_text)을 주면 다음 지시사항에 따라 예시와 같이 결과를 생성해줘.
      <지시사항>
      1. issue는 원문의 주요 사항에 대한 요약이다. 유사한 issue는 하나로 만들어줘. 예를 들어, "화질 우수", "좋은 화질", "뛰어난 화질" 등은 "우수한 화질"로 통합하고, "캠핑 및 가정에서 사용", "캠핑 및 집에서 사용 만족" 등은 "캠핑 및 가정 사용"으로 통합한다.
      2. 각 issue에 대해 감정분석 값을 도출하여 sentiment로 표현한다.
      3. sentiment는 긍정/부정을 평가할 수 없는 경우에는 중립으로 표현한다.
      4. 답변은 코드블록이나 마크다운 포맷 없이, 순수한 JSON 포맷으로 제공한다. ```json 같은 형식은 사용하지 않는다.
      </지시사항>

    few_shot_examples: |
      <예시>
      {
        "raw_text": "자취하는데 뭔 티비야 .. 하면서 노트북이나 패드로 유튜브, ott 시청했었는데 확실히 더 큰 화면으로 보니까 너무 조아요설거지하거나 가구 배치 바꿀 때도 쉽게 움직여서 이동시킬 수 있으니까 정말 좋습니다..삶의 질이 향상됐어요 ㅎㅎ",
        "issues": [
          "더 큰 화면으로 OTT 시청 좋음",
          "이동 편리"
        ],
        "sentiments": {
          "더 큰 화면으로 OTT 시청 좋음": "긍정",
          "이동 편리": "긍정"
        },
        "sentiment_all": "긍정",
        "theme": [
          "제품 실용성",
          "제품 편의성"
        ]
      },
      {
        "raw_text": "핸드폰으로 ott를 보다보니 항상 아쉬웠는데 고민고민하다질렀어요~^^ 주문후 다음날 오전에 배송설치했고 생각한대로 디자인이나 품질 맘에들어요",
        "issues": [
          "OTT 시청",
          "빠른 배송",
          "디자인 만족",
          "품질 만족"
        ],
        "sentiments": {
          "OTT 시청": "중립",
          "빠른 배송": "긍정",
          "디자인 만족": "긍정",
          "품질 만족": "긍정"
        },
        "sentiment_all": "긍정",
        "theme": [
          "제품 실용성",
          "배송",
          "제품 품질",
          "디자인"
        ]
      },
      {
        "raw_text": "너무 좋아요무겁지만 바퀴가 있어 이동이 용이 하고사운드,화질등 나무랄게 없어요",
        "issues": [
          "무겁지만 이동 용이",
          "우수한 사운드",
          "우수한 화질"
        ],
        "sentiments": {
          "무겁지만 이동 용이": "중립",
          "우수한 사운드": "긍정",
          "우수한 화질": "긍정"
        },
        "sentiment_all": "긍정",
        "theme": [
          "제품 편의성",
          "제품 품질"
        ]
      },
      {
        "raw_text": "밥 먹을때 자기전에 이동하면서 보고있는데 너무 편하고 좋아요",
        "issues": [
          "이동 편리",
          "식사시간 시청",
          "자기전 시청"
        ],
        "sentiments": {
          "이동 편리": "긍정",
          "식사시간 시청": "중립",
          "자기전 시청": "중립"
        },
        "sentiment_all": "긍정",
        "theme": [
          "제품 편의성",
          "제품 실용성"
        ]
      },
      {
        "raw_text": "ott 유튜브만 보는분들에게 적극추천 리모컨으로도 터치로도 작동 잘됩니다~",
        "issues": [
          "OTT/유튜브 시청 좋음",
          "리모컨",
          "터치 작동"
        ],
        "sentiments": {
          "OTT/유튜브 시청 좋음": "긍정",
          "리모컨": "긍정",
          "터치 작동": "긍정"
        },
        "sentiment_all": "긍정",
        "theme": [
          "제품 실용성",
          "제품 편의성"
        ]
      },
      {
        "raw_text": "TV 잘 안보시는 분들은 스탠바이미 추천드립니다!",
        "issues": [
          "TV 미시청자 추천"
        ],
        "sentiments": {
          "TV 미시청자 추천": "긍정"
        },
        "sentiment_all": "긍정",
        "theme": [
          "제품 추천"
        ]
      },
      {
        "raw_text": "매우 실용적이고 디자인 및 내구성도 훌륭해보입니다. TV 없는 가정에서는 매우 유용하게 쓰입니다. 이동도 쉬워서 편리하고 화질이나 음량도 만족스럽습니다. 망설이는 분들께 강추합니다.",
        "issues": [
          "실용성",
          "훌륭한 디자인",
          "내구성",
          "TV없는 가정에서 유용",
          "편리한 이동",
          "만족스러운 화질",
          "음량",
          "강추"
        ],
        "sentiments": {
          "실용성": "긍정",
          "훌륭한 디자인": "긍정",
          "내구성": "긍정",
          "TV없는 가정에서 유용": "긍정",
          "편리한 이동": "긍정",
          "만족스러운 화질": "긍정",
          "음량": "긍정",
          "강추": "긍정"
        },
        "sentiment_all": "긍정",
        "theme": [
          "제품 실용성",
          "디자인",
          "제품 품질",
          "제품 편의성",
          "제품 만족/추천"
        ]
      },
      {
        "raw_text": "저렴한 가격에 배송 잘 받았어요진작에 살걸 그랬어요너무좋아요",
        "issues": [
          "저렴한 가격",
          "배송 만족",
          "좋은 제품"
        ],
        "sentiments": {
          "저렴한 가격": "긍정",
          "배송 만족": "긍정",
          "좋은 제품": "긍정"
        },
        "sentiment_all": "긍정",
        "theme": [
          "제품 가격",
          "배송",
          "제품 만족/추천"
        ]
      },
      {
        "raw_text": "캠핑의 질이 수직 상승했습니다. 룸앤티비랑 고민하다가 이걸로 선택했는데 탁월한 선택입니다. 소리도 빵빵하고 화질도 좋습니다. 너무 무거운게 약간 불편하지만 캠핑장에서이런 티비를 볼 수 있다는게 너무 좋아요.",
        "issues": [
          "좋은 소리",
          "좋은 화질",
          "무거움",
          "캠핑장에서 만족"
        ],
        "sentiments": {
          "좋은 소리": "긍정",
          "좋은 화질": "긍정",
          "무거움": "부정",
          "캠핑장에서 만족": "긍정"
        },
        "sentiment_all": "긍정",
        "theme": [
          "제품 품질",
          "제품 실용성",
          "제품 편의성"
        ]
      },
      {
        "raw_text": "이동하기편하고 작은핸드폰으로 유튜브보는것보다 훨씬조코 편하네요 인터넷 티비 게임까지 할수 잇는 컴퓨터라고 생각하고 사용하려고 합니다 제품이 무게만 가볍다면 정말완벽할 꺼라고 생각합니다 너무 무거워서 아이나 여자는 움직이기 힘드네요",
        "issues": [
          "이동 편리",
          "유튜브",
          "인터넷",
          "티비",
          "게임 가능",
          "무거움"
        ],
        "sentiments": {
          "이동 편리": "긍정",
          "유튜브": "긍정",
          "인터넷": "긍정",
          "티비": "긍정",
          "게임 가능": "긍정",
          "무거움": "긍정"
        },
        "sentiment_all": "긍정",
        "theme": [
          "제품 편의성",
          "제품 실용성"
        ]
      }
      </예시>

  theme:
    instructions: |
      넌 글을 클러스터링하는 전문가야. 다음 지시사항에 따라 예시와 같이 결과를 생성해줘.
      <지시사항>
      1. 제시한 issues를 클러스터링하여 theme(클러스터의 이름)을 도출한다.
      2. theme은 issues를 기반으로 유추하여 생성한다. 예를 들어, issues가 "화질 우수", "좋은 화질", "뛰어난 화질" 등이면 theme는 "제품 품질"로 통합하고, issues가 "캠핑 및 가정에서 사용", "캠핑 및 집에서 사용 만족" 등이면 theme는 "제품 실용성"으로 통합한다.
      3. 답변은 코드블록이나 마크다운 포맷 없이, 순수한 JSON 포맷으로 제공한다. ```json 같은 형식은 사용하지 않는다.
      형식은 다음과 같다.
            {
        "theme1": [issue1, issue2, ...],
        "theme2": [issue3, issue4, ...],
      }
      4. 하나의 theme 내에 중복된 issue가 있으면 안된다.
      5. 모든 issues는 theme에 속해야 한다.

      </지시사항>
    few_shot_examples: |
      <예시>
      {
        "제품 실용성": ["OTT 시청", "식사시간 시청", "자기전 시청", "인터넷", "게임 가능"],
        "제품 편의성": ["이동 편리", "리모컨", "터치 작동"],
        "제품 품질": ["품질 만족", "우수한 사운드", "우수한 화질"],
        "제품 유용성": ["유용성", "TV 미시청자 추천", "TV없는 가정에서 유용", "캠핑장에서 만족"],
        "디자인": ["디자인 만족", "훌륭한 디자인", "예쁨"],
        "배송": ["빠른 배송", "배송 만족"],
        "가격": ["저렴한 가격"],
        "제품 만족/추천": ["기대", "만족", "강추"]
      }
      </예시>