data_crawling:
  exclude_phrase:
    - "제품을 협찬받아 작성되었습니다"
    - "제품을 제공받아 작성하였습니다"
    - "협찬을 받아 작성된 포스팅입니다"
    - "소정의 사례금을 받고 작성되었습니다"
    - "사례금을 받아 작성한 글입니다"
    - "제공한 금전적 보상을 받고 작성되었습니다"
    - "제품을 협찬받고 소정의 사례금을 받아 작성되었습니다"
    - "협찬과 사례금을 받아 작성된 리뷰입니다"
    - "제품 협찬과 함께 작성되었습니다"
    - "제품과 사례금을 제공받아 작성되었습니다"
    - "광고를 포함하고 있습니다"
    - "홍보를 목적으로 작성되었습니다"

  exclude_hashtag:
    - "#광고"
    - "#협찬"
    - "#스폰서"
    - "#지원받음"
    - "#유료광고"
    - "#광고포함"
    - "#제휴"
    - "#파트너십"
    - "#홍보"
    - "#광고제휴"
    - "#광고리뷰"
    - "#프로모션"
    - "#AD"
    - "#Sponsored"
    - "#SponsoredPost"
    - "#PaidPartnership"
    - "#PaidPromotion"
    - "#Promotion"
    - "#PR"
preprocessing:
  filter:
    - lgstanbymeclub
    - imsanbu
    - campingfirst

gptapi:
  sentiment:
    instructions: |
      넌 글을 요약하는 전문가야. 어떤 제품에 대한 리뷰 원문을 주면 다음 지시사항에 따라 예시와 같이 결과를 받고 싶어.
      <지시사항>
      1. raw_text는 제품에 대한 리뷰 원문이다.
      2. issue는 원문의 주요 사항에 대한 요약이다.
      3. 각 issue에 대해 감정분석 값을 도출하여 sentiment로 표현한다.
      4. sentiment는 긍정/부정을 평가할 수 없는 경우에는 중립으로 표현한다.
      5. 답변은 코드블록이나 마크다운 포맷 없이, 순수한 JSON 포맷으로 제공한다. ```json 같은 형식은 사용하지 않는다.
      </지시사항>

    few_shot_examples: |
      <예시>
      {
        "raw_text": "자취하는데 뭔 티비야 .. 하면서 노트북이나 패드로 유튜브, ott 시청했었는데 확실히 더 큰 화면으로 보니까 너무 조아요설거지하거나 가구 배치 바꿀 때도 쉽게 움직여서 이동시킬 수 있으니까 정말 좋습니다..삶의 질이 향상됐어요 ㅎㅎ",
        "issues": [
          "더 큰 화면으로 OTT 시청 좋음",
          "이동 편리"
        ],
        "sentiments": {
          "더 큰 화면으로 OTT 시청 좋음": "긍정",
          "이동 편리": "긍정"
        },
        "sentiment_all": "긍정",
        "theme": [
          "제품 실용성",
          "제품 편의성"
        ]
      },
      {
        "raw_text": "핸드폰으로 ott를 보다보니 항상 아쉬웠는데 고민고민하다질렀어요~^^ 주문후 다음날 오전에 배송설치했고 생각한대로 디자인이나 품질 맘에들어요",
        "issues": [
          "OTT 시청",
          "빠른 배송",
          "디자인 만족",
          "품질 만족"
        ],
        "sentiments": {
          "OTT 시청": "중립",
          "빠른 배송": "긍정",
          "디자인 만족": "긍정",
          "품질 만족": "긍정"
        },
        "sentiment_all": "긍정",
        "theme": [
          "제품 실용성",
          "배송",
          "제품 품질",
          "디자인"
        ]
      },
      {
        "raw_text": "너무 좋아요무겁지만 바퀴가 있어 이동이 용이 하고사운드,화질등 나무랄게 없어요",
        "issues": [
          "무겁지만 이동 용이",
          "우수한 사운드",
          "우수한 화질"
        ],
        "sentiments": {
          "무겁지만 이동 용이": "중립",
          "우수한 사운드": "긍정",
          "우수한 화질": "긍정"
        },
        "sentiment_all": "긍정",
        "theme": [
          "제품 편의성",
          "제품 품질"
        ]
      },
      {
        "raw_text": "밥 먹을때 자기전에 이동하면서 보고있는데 너무 편하고 좋아요",
        "issues": [
          "이동 편리",
          "식사시간 시청",
          "자기전 시청"
        ],
        "sentiments": {
          "이동 편리": "긍정",
          "식사시간 시청": "중립",
          "자기전 시청": "중립"
        },
        "sentiment_all": "긍정",
        "theme": [
          "제품 편의성",
          "제품 실용성"
        ]
      },
      {
        "raw_text": "ott 유튜브만 보는분들에게 적극추천 리모컨으로도 터치로도 작동 잘됩니다~",
        "issues": [
          "OTT/유튜브 시청 좋음",
          "리모컨",
          "터치 작동"
        ],
        "sentiments": {
          "OTT/유튜브 시청 좋음": "긍정",
          "리모컨": "긍정",
          "터치 작동": "긍정"
        },
        "sentiment_all": "긍정",
        "theme": [
          "제품 실용성",
          "제품 편의성"
        ]
      },
      {
        "raw_text": "TV 잘 안보시는 분들은 스탠바이미 추천드립니다!",
        "issues": [
          "TV 미시청자 추천"
        ],
        "sentiments": {
          "TV 미시청자 추천": "긍정"
        },
        "sentiment_all": "긍정",
        "theme": [
          "제품 추천"
        ]
      },
      {
        "raw_text": "매우 실용적이고 디자인 및 내구성도 훌륭해보입니다. TV 없는 가정에서는 매우 유용하게 쓰입니다. 이동도 쉬워서 편리하고 화질이나 음량도 만족스럽습니다. 망설이는 분들께 강추합니다.",
        "issues": [
          "실용성",
          "훌륭한 디자인",
          "내구성",
          "TV없는 가정에서 유용",
          "편리한 이동",
          "만족스러운 화질",
          "음량",
          "강추"
        ],
        "sentiments": {
          "실용성": "긍정",
          "훌륭한 디자인": "긍정",
          "내구성": "긍정",
          "TV없는 가정에서 유용": "긍정",
          "편리한 이동": "긍정",
          "만족스러운 화질": "긍정",
          "음량": "긍정",
          "강추": "긍정"
        },
        "sentiment_all": "긍정",
        "theme": [
          "제품 실용성",
          "디자인",
          "제품 품질",
          "제품 편의성",
          "제품 만족/추천"
        ]
      },
      {
        "raw_text": "저렴한 가격에 배송 잘 받았어요진작에 살걸 그랬어요너무좋아요",
        "issues": [
          "저렴한 가격",
          "배송 만족",
          "좋은 제품"
        ],
        "sentiments": {
          "저렴한 가격": "긍정",
          "배송 만족": "긍정",
          "좋은 제품": "긍정"
        },
        "sentiment_all": "긍정",
        "theme": [
          "제품 가격",
          "배송",
          "제품 만족/추천"
        ]
      },
      {
        "raw_text": "캠핑의 질이 수직 상승했습니다. 룸앤티비랑 고민하다가 이걸로 선택했는데 탁월한 선택입니다. 소리도 빵빵하고 화질도 좋습니다. 너무 무거운게 약간 불편하지만 캠핑장에서이런 티비를 볼 수 있다는게 너무 좋아요.",
        "issues": [
          "좋은 소리",
          "좋은 화질",
          "무거움",
          "캠핑장에서 만족"
        ],
        "sentiments": {
          "좋은 소리": "긍정",
          "좋은 화질": "긍정",
          "무거움": "부정",
          "캠핑장에서 만족": "긍정"
        },
        "sentiment_all": "긍정",
        "theme": [
          "제품 품질",
          "제품 실용성",
          "제품 편의성"
        ]
      },
      {
        "raw_text": "이동하기편하고 작은핸드폰으로 유튜브보는것보다 훨씬조코 편하네요 인터넷 티비 게임까지 할수 잇는 컴퓨터라고 생각하고 사용하려고 합니다 제품이 무게만 가볍다면 정말완벽할 꺼라고 생각합니다 너무 무거워서 아이나 여자는 움직이기 힘드네요",
        "issues": [
          "이동 편리",
          "유튜브",
          "인터넷",
          "티비",
          "게임 가능",
          "무거움"
        ],
        "sentiments": {
          "이동 편리": "긍정",
          "유튜브": "긍정",
          "인터넷": "긍정",
          "티비": "긍정",
          "게임 가능": "긍정",
          "무거움": "긍정"
        },
        "sentiment_all": "긍정",
        "theme": [
          "제품 편의성",
          "제품 실용성"
        ]
      }
      </예시>

  theme:
    instructions: |
      <지시사항>
      1. 여러 리뷰에서 도출된 이슈 목록을 바탕으로 유사한 의미를 가진 이슈들끼리 클러스터링을 수행하여 theme을 도출해줘.
      2. 각 theme은 유사한 의미를 가진 issue들을 하나로 묶은 그룹이어야 한다.
      3. theme 이름은 각 그룹의 대표적인 성격을 잘 나타낼 수 있도록 명명해야 한다.
      4. 답변은 코드블록이나 마크다운 포맷 없이, 순수한 JSON 포맷으로 제공한다. ```json 같은 형식은 사용하지 않는다.
      </지시사항>

      <예시>
      {
        "배송 관련": ["빠른 배송", "배송 지연"],
        "서비스 관련": ["고객 서비스", "친절한 기사", "친절한 서비스", "친절한 답변", "친절한 판매자", "친절한 상담", "친절한 설치 기사"],
        "제품 품질 관련": ["좋은 제품", "제품 만족", "품질 좋음", "하자 없는 제품"],
        "가격 관련": ["저렴한 가격", "가격 경쟁력"]
      }
      </예시>