data_crawling:
  exclude_phrase:
    - "제품을 협찬받아 작성되었습니다"
    - "제품을 제공받아 작성하였습니다"
    - "협찬을 받아 작성된 포스팅입니다"
    - "소정의 사례금을 받고 작성되었습니다"
    - "사례금을 받아 작성한 글입니다"
    - "제공한 금전적 보상을 받고 작성되었습니다"
    - "제품을 협찬받고 소정의 사례금을 받아 작성되었습니다"
    - "협찬과 사례금을 받아 작성된 리뷰입니다"
    - "제품 협찬과 함께 작성되었습니다"
    - "제품과 사례금을 제공받아 작성되었습니다"
    - "광고를 포함하고 있습니다"
    - "홍보를 목적으로 작성되었습니다"

  exclude_hashtag:
    - "#광고"
    - "#협찬"
    - "#스폰서"
    - "#지원받음"
    - "#유료광고"
    - "#광고포함"
    - "#제휴"
    - "#파트너십"
    - "#홍보"
    - "#광고제휴"
    - "#광고리뷰"
    - "#프로모션"
    - "#AD"
    - "#Sponsored"
    - "#SponsoredPost"
    - "#PaidPartnership"
    - "#PaidPromotion"
    - "#Promotion"
    - "#PR"
preprocessing:
  filter:
    - lgstanbymeclub
    - imsanbu
    - campingfirst

gptapi:
  system_content:
    role_summarize: |
      넌 글을 요약하는 전문가야. 내용을 입력하면 아래 지시사항에 따라 예시처럼 요약해줘.
      <지시사항>
      1. 원본 텍스트를 요약해줘.
      2. 문장 형태로 답하지 않는다.
      3. 요약문은 형용사와 명사를 중심으로 작성한다.
      4. 상황(OTT시청, 식사시간, 자기 전, TV없는 가정 등)에 대한 요약도 포함한다.
      5. 답변은 [issue]로 나타낸다.

      </지시사항>

      <예시1>
      [원본 텍스트]
      선물용으로 구매했는데 빠른 배송 감사
      
      [issue]
      빠른 배송
      </예시1>

      <예시2>
      [원본 텍스트]
      4일이내 설치배송연락받았고 원하는날 안착완료^^제품 설치 서비스 모두모두 만족이요

      [issue]
      빠른 설치, 서비스 만족
      </예시2>

      <예시3>
      [원본 텍스트]
      자취하는데 뭔 티비야 .. 하면서 노트북이나 패드로 유튜브, ott 시청했었는데 확실히 더 큰 화면으로 보니까 너무 조아요설거지하거나 가구 배치 바꿀 때도 쉽게 움직여서 이동시킬 수 있으니까 정말 좋습니다..삶의 질이 향상됐어요 ㅎㅎ

      [issue]
      큰 화면, 이동 편리, 삶의 질 향상, OTT 시청
      </예시3>
      

  assistant_content:
    senti_categ: |
      요약된 내용(issue)을 예시처럼 카테고리화해줘.
      빠른, 느린, 만족, 불만족 등 평가는 지양하고, 설치, 배송, 서비스 등 구체적인 카테고리로 분류해줘.
      결과는 쉼표로 구분하고, [theme]으로 나타낸다.
      그리고 각각의 카테고리에 대한 감성을 '매우 긍정', '긍정', '중립', '부정', '매우 부정'으로 평가하여 [sentiment]로 나타낸다.
      그리고 전체적인 감성은 [sentiment]의 결과를 종합하여 '매우 긍정', '긍정', '중립', '부정', '매우 부정'으로 평가하여 [전체 감성]으로 나타낸다.

      <예시1>
      [theme]
      설치, 서비스, 배송

      [sentiment]
      설치: 긍정, 서비스: 긍정, 배송: 부정
      
      [전체 감성]
      긍정
      </예시1>
      