gptapi:
  parameters:
    model: "gpt-4o"
    temperature: 0.5
    stream: False

  sentiment:
    instructions: |
      넌 글을 요약하는 전문가야. 어떤 제품에 대한 리뷰 원문(raw_text)을 주면 다음 지시사항에 따라 예시와 같이 결과를 생성해줘.
      <지시사항>
      1. issue는 원문의 주요 사항을 요약한 것입니다. 동일하거나 유사한 표현은 하나의 issue로 통합합니다. 예: “좋은 화질”, “뛰어난 화질” → “우수한 화질”, “가정 및 캠핑에서 사용” → “캠핑 및 가정에서 사용”.
      2. 각 issue에 대해 감정 분석을 수행하고 sentiment로 표현합니다.
      3. sentiment는 긍정, 부정, 중립 중 하나로 표시하며, 명확한 감정 평가가 어려운 경우 중립으로 처리합니다.
      4. 응답은 순수 JSON 형식으로만 제공하며, 코드블록이나 마크다운 포맷은 사용하지 않습니다.
      </지시사항>

    few_shot_examples: |
      <예시>
      {
        "raw_text": "자취하는데 뭔 티비야 .. 하면서 노트북이나 패드로 유튜브, ott 시청했었는데 확실히 더 큰 화면으로 보니까 너무 조아요설거지하거나 가구 배치 바꿀 때도 쉽게 움직여서 이동시킬 수 있으니까 정말 좋습니다..삶의 질이 향상됐어요 ㅎㅎ",
        "issue": [
          "더 큰 화면으로 OTT 시청 좋음",
          "이동 편리"
        ],
        "sentiment": {
          "더 큰 화면으로 OTT 시청 좋음": "긍정",
          "이동 편리": "긍정"
        },
        "sentiment_all": "긍정"
      },
      {
        "raw_text": "핸드폰으로 ott를 보다보니 항상 아쉬웠는데 고민고민하다질렀어요~^^ 주문후 다음날 오전에 배송설치했고 생각한대로 디자인이나 품질 맘에들어요",
        "issue": [
          "OTT 시청",
          "빠른 배송",
          "디자인 만족",
          "품질 만족"
        ],
        "sentiment": {
          "OTT 시청": "중립",
          "빠른 배송": "긍정",
          "디자인 만족": "긍정",
          "품질 만족": "긍정"
        },
        "sentiment_all": "긍정"
      },
      {
        "raw_text": "너무 좋아요무겁지만 바퀴가 있어 이동이 용이 하고사운드,화질등 나무랄게 없어요",
        "issue": [
          "무겁지만 이동 용이",
          "우수한 사운드",
          "우수한 화질"
        ],
        "sentiment": {
          "무겁지만 이동 용이": "중립",
          "우수한 사운드": "긍정",
          "우수한 화질": "긍정"
        },
        "sentiment_all": "긍정"
      },
      {
        "raw_text": "밥 먹을때 자기전에 이동하면서 보고있는데 너무 편하고 좋아요",
        "issue": [
          "이동 편리",
          "식사시간 시청",
          "자기전 시청"
        ],
        "sentiment": {
          "이동 편리": "긍정",
          "식사시간 시청": "중립",
          "자기전 시청": "중립"
        },
        "sentiment_all": "긍정"
      },
      {
        "raw_text": "ott 유튜브만 보는분들에게 적극추천 리모컨으로도 터치로도 작동 잘됩니다~",
        "issue": [
          "OTT/유튜브 시청 좋음",
          "리모컨",
          "터치 작동"
        ],
        "sentiment": {
          "OTT/유튜브 시청 좋음": "긍정",
          "리모컨": "긍정",
          "터치 작동": "긍정"
        },
        "sentiment_all": "긍정"
      },
      {
        "raw_text": "TV 잘 안보시는 분들은 스탠바이미 추천드립니다!",
        "issue": [
          "TV 미시청자 추천"
        ],
        "sentiment": {
          "TV 미시청자 추천": "긍정"
        },
        "sentiment_all": "긍정"
      },
      {
        "raw_text": "매우 실용적이고 디자인 및 내구성도 훌륭해보입니다. TV 없는 가정에서는 매우 유용하게 쓰입니다. 이동도 쉬워서 편리하고 화질이나 음량도 만족스럽습니다. 망설이는 분들께 강추합니다.",
        "issue": [
          "실용성",
          "훌륭한 디자인",
          "내구성",
          "TV없는 가정에서 유용",
          "편리한 이동",
          "만족스러운 화질",
          "음량",
          "강추"
        ],
        "sentiment": {
          "실용성": "긍정",
          "훌륭한 디자인": "긍정",
          "내구성": "긍정",
          "TV없는 가정에서 유용": "긍정",
          "편리한 이동": "긍정",
          "만족스러운 화질": "긍정",
          "음량": "긍정",
          "강추": "긍정"
        },
        "sentiment_all": "긍정"
      },
      {
        "raw_text": "저렴한 가격에 배송 잘 받았어요진작에 살걸 그랬어요너무좋아요",
        "issue": [
          "저렴한 가격",
          "배송 만족",
          "좋은 제품"
        ],
        "sentiment": {
          "저렴한 가격": "긍정",
          "배송 만족": "긍정",
          "좋은 제품": "긍정"
        },
        "sentiment_all": "긍정"
      },
      {
        "raw_text": "캠핑의 질이 수직 상승했습니다. 룸앤티비랑 고민하다가 이걸로 선택했는데 탁월한 선택입니다. 소리도 빵빵하고 화질도 좋습니다. 너무 무거운게 약간 불편하지만 캠핑장에서이런 티비를 볼 수 있다는게 너무 좋아요.",
        "issue": [
          "좋은 소리",
          "좋은 화질",
          "무거움",
          "캠핑장에서 만족"
        ],
        "sentiment": {
          "좋은 소리": "긍정",
          "좋은 화질": "긍정",
          "무거움": "부정",
          "캠핑장에서 만족": "긍정"
        },
        "sentiment_all": "긍정"
      },
      {
        "raw_text": "이동하기편하고 작은핸드폰으로 유튜브보는것보다 훨씬조코 편하네요 인터넷 티비 게임까지 할수 잇는 컴퓨터라고 생각하고 사용하려고 합니다 제품이 무게만 가볍다면 정말완벽할 꺼라고 생각합니다 너무 무거워서 아이나 여자는 움직이기 힘드네요",
        "issue": [
          "이동 편리",
          "유튜브",
          "인터넷",
          "티비",
          "게임 가능",
          "무거움"
        ],
        "sentiment": {
          "이동 편리": "긍정",
          "유튜브": "긍정",
          "인터넷": "긍정",
          "티비": "긍정",
          "게임 가능": "긍정",
          "무거움": "긍정"
        },
        "sentiment_all": "긍정"
      }
      </예시>

  theme:
    instructions: |
      You are an assistant that helps cluster and categorize product issues.
      <지시사항>
      1. 이슈들을 의미적으로 비슷한 그룹으로 나누고, 각 그룹의 공통 테마(theme)를 도출해줘
      2. 누락되는 이슈 없이 각각의 이슈는 하나의 테마에 속해야 한다.
      3. 답변은 코드블록이나 마크다운 포맷 없이, 순수한 JSON 포맷으로 제공한다. ```json 같은 형식은 사용하지 않는다.
      </지시사항>

    few_shot_examples: |
      {
        "화질 만족": ["화질 우수", "좋은 화질", "선명한 화질"],
        "사용 편의성": ["리모컨 사용 편리", "메뉴 구성 직관적"],
        "배송 서비스": ["빠른 배송", "친절한 배송"]
      }

data_crawling:
  exclude_phrase:
    - "제품을 협찬받아 작성되었습니다"
    - "제품을 제공받아 작성하였습니다"
    - "협찬을 받아 작성된 포스팅입니다"
    - "소정의 사례금을 받고 작성되었습니다"
    - "사례금을 받아 작성한 글입니다"
    - "제공한 금전적 보상을 받고 작성되었습니다"
    - "제품을 협찬받고 소정의 사례금을 받아 작성되었습니다"
    - "협찬과 사례금을 받아 작성된 리뷰입니다"
    - "제품 협찬과 함께 작성되었습니다"
    - "제품과 사례금을 제공받아 작성되었습니다"
    - "광고를 포함하고 있습니다"
    - "홍보를 목적으로 작성되었습니다"

  exclude_hashtag:
    - "#광고"
    - "#협찬"
    - "#스폰서"
    - "#지원받음"
    - "#유료광고"
    - "#광고포함"
    - "#제휴"
    - "#파트너십"
    - "#홍보"
    - "#광고제휴"
    - "#광고리뷰"
    - "#프로모션"
    - "#AD"
    - "#Sponsored"
    - "#SponsoredPost"
    - "#PaidPartnership"
    - "#PaidPromotion"
    - "#Promotion"
    - "#PR"
preprocessing:
  filter:
    - lgstanbymeclub
    - imsanbu
    - campingfirst